### 라이브러리 불러오기

In [1]:
import openpyxl

In [2]:
import numpy as np
import pandas as pd
# import glob

In [3]:
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
plt.rc('font', family='Malgun Gothic')
sns.set(font="Malgun Gothic",
        rc={"axes.unicode_minus":False}, # 마이너스 부호 깨짐 현상 해결
        style='darkgrid')  

import warnings
warnings.filterwarnings(action='ignore')
%config InlineBackend.figure_format = 'retina'

In [4]:
path = 'data\강서구 행정동별 인구밀도 2022.csv'
data = pd.read_csv(path)

data.head(20)

    동별(1)  동별(2)  동별(3)    2022  2022.1      2022.2
0   동별(1)  동별(2)  동별(3)  인구 (명)  면적 (㎢)  인구밀도 (명/㎢)
1      합계    강서구     소계  574638   41.45       13863
2      합계    강서구    염창동   41628    1.74       23924
3      합계    강서구   등촌1동   24991    0.64       39048
4      합계    강서구   등촌2동   19855    0.92       21582
5      합계    강서구   등촌3동   30025    0.79       38006
6      합계    강서구   화곡본동   34121    0.98       34817
7      합계    강서구   화곡2동   17785    0.45       39522
8      합계    강서구   화곡3동   21603    0.53       40760
9      합계    강서구   화곡4동   20514    0.82       25017
10     합계    강서구   화곡6동   25303    1.11       22795
11     합계    강서구   화곡8동   24415    0.53       46066
12     합계    강서구   가양1동   34359    4.70        7310
13     합계    강서구   가양2동   13902    1.00       13902
14     합계    강서구   가양3동   14678    0.50       29356
15     합계    강서구   발산1동   36236    2.94       12325
16     합계    강서구    공항동   30927   10.87        2845
17     합계    강서구   방화1동   42851    1.48       28953
18     합계    강서구   방화2동   23371    6.41        3646
19     합계    강서구   방화3동   22544    2.55        8841

In [5]:
data.columns

Index(['동별(1)', '동별(2)', '동별(3)', '2022', '2022.1', '2022.2'], dtype='object')

In [6]:
data = data.rename(columns=data.iloc[0])
data.drop(0, inplace=True)
data = data[['동별(3)', '인구 (명)', '면적 (㎢)', '인구밀도 (명/㎢)']]
data

   동별(3)  인구 (명) 면적 (㎢) 인구밀도 (명/㎢)
1     소계  574638  41.45      13863
2    염창동   41628   1.74      23924
3   등촌1동   24991   0.64      39048
4   등촌2동   19855   0.92      21582
5   등촌3동   30025   0.79      38006
6   화곡본동   34121   0.98      34817
7   화곡2동   17785   0.45      39522
8   화곡3동   21603   0.53      40760
9   화곡4동   20514   0.82      25017
10  화곡6동   25303   1.11      22795
11  화곡8동   24415   0.53      46066
12  가양1동   34359   4.70       7310
13  가양2동   13902   1.00      13902
14  가양3동   14678   0.50      29356
15  발산1동   36236   2.94      12325
16   공항동   30927  10.87       2845
17  방화1동   42851   1.48      28953
18  방화2동   23371   6.41       3646
19  방화3동   22544   2.55       8841
20  화곡1동   52647   1.12      47006
21  우장산동   42883   1.36      31532

### 강서구 전체 면적 및 인구 현황

In [10]:
gu = data.iloc[[0]]
gu

  동별(3)  인구 (명) 면적 (㎢) 인구밀도 (명/㎢)
1    소계  574638  41.45      13863

### 행정동별 면적 및 인구 현황

In [13]:
dong = data.loc[2:, :]
dong.reset_index(drop=True, inplace=True)
dong

   동별(3) 인구 (명) 면적 (㎢) 인구밀도 (명/㎢)
0    염창동  41628   1.74      23924
1   등촌1동  24991   0.64      39048
2   등촌2동  19855   0.92      21582
3   등촌3동  30025   0.79      38006
4   화곡본동  34121   0.98      34817
5   화곡2동  17785   0.45      39522
6   화곡3동  21603   0.53      40760
7   화곡4동  20514   0.82      25017
8   화곡6동  25303   1.11      22795
9   화곡8동  24415   0.53      46066
10  가양1동  34359   4.70       7310
11  가양2동  13902   1.00      13902
12  가양3동  14678   0.50      29356
13  발산1동  36236   2.94      12325
14   공항동  30927  10.87       2845
15  방화1동  42851   1.48      28953
16  방화2동  23371   6.41       3646
17  방화3동  22544   2.55       8841
18  화곡1동  52647   1.12      47006
19  우장산동  42883   1.36      31532

In [16]:
dong = dong.rename(columns={'동별(3)':'행정동'})
dong

     행정동 인구 (명) 면적 (㎢) 인구밀도 (명/㎢)
0    염창동  41628   1.74      23924
1   등촌1동  24991   0.64      39048
2   등촌2동  19855   0.92      21582
3   등촌3동  30025   0.79      38006
4   화곡본동  34121   0.98      34817
5   화곡2동  17785   0.45      39522
6   화곡3동  21603   0.53      40760
7   화곡4동  20514   0.82      25017
8   화곡6동  25303   1.11      22795
9   화곡8동  24415   0.53      46066
10  가양1동  34359   4.70       7310
11  가양2동  13902   1.00      13902
12  가양3동  14678   0.50      29356
13  발산1동  36236   2.94      12325
14   공항동  30927  10.87       2845
15  방화1동  42851   1.48      28953
16  방화2동  23371   6.41       3646
17  방화3동  22544   2.55       8841
18  화곡1동  52647   1.12      47006
19  우장산동  42883   1.36      31532

In [33]:
dong.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   행정동         20 non-null     object
 1   인구 (명)      20 non-null     object
 2   면적 (㎢)      20 non-null     object
 3   인구밀도 (명/㎢)  20 non-null     object
dtypes: object(4)
memory usage: 768.0+ bytes

In [36]:
dong['인구 (명)'] = dong['인구 (명)'].astype('int64')
dong['면적 (㎢)'] = dong['면적 (㎢)'].astype('float64')
dong['인구밀도 (명/㎢)'] = dong['인구밀도 (명/㎢)'].astype('int64')
dong.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   행정동         20 non-null     object
 1   인구 (명)      20 non-null     int64
 2   면적 (㎢)      20 non-null     float64
 3   인구밀도 (명/㎢)  20 non-null     int64
dtypes: float64(1), int64(2), object(1)
memory usage: 768.0+ bytes

In [37]:
dong.to_csv('data/fixed/행정동별 인구밀도.csv', index=False)

### 행정동별 고령인구

In [30]:
path = 'data/2022년 행정동별 고령 인구.csv'
data = pd.read_csv(path)
data.drop('Unnamed: 0', axis=1, inplace=True)
data.reset_index(drop=True, inplace=True)
data.head(20)

,동별,소계,65~69세,70~74세,75~79세,80~84세,85~89세,90~94세,95~99세,100세 이상,65세 이상,65세 이상 비율
0,화곡1동,52647,3232,2356,1591,990,387,145,34,5,8353,0.158661
1,방화1동,42851,2708,1815,1177,783,376,142,41,8,6674,0.155749
2,등촌3동,30025,2489,1566,1163,934,591,257,59,6,6474,0.215620
3,우장산동,42883,2356,1691,1131,644,269,100,17,6,5945,0.138633
4,방화3동,22544,1892,1389,960,694,396,159,43,4,5141,0.228043
5,화곡본동,34121,1976,1331,917,558,261,88,22,7,4899,0.143577
6,발산1동,36236,1788,1329,948,621,302,116,25,5,4832,0.133348
7,방화2동,23371,1794,1181,899,671,349,114,28,3,4690,0.200676
8,염창동,41628,1855,1201,750,512,243,71,18,2,4409,0.105914
9,화곡8동,24415,1647,1228,896,548,192,60,12,3,4394,0.179971
10,공항동,30927,1649,1051,809,537,248,104,28,2,4180,0.135157
11,화곡3동,21603,1587,1173,759,484,184,78,19,2,4102,0.189881
12,가양2동,13902,1625,1056,721,549,313,105,25,2,4083,0.293699
13,화곡6동,25303,1643,1117,643,454,209,75,15,3,3950,0.156108
14,화곡4동,20514,1507,1028,744,472,212,73,15,1,3840,0.187189
15,가양3동,14678,1327,975,704,525,234,72,27,3,3633,0.247513
16,등촌2동,19855,1308,898,537,338,173,81,19,2,3183,0.160312
17,가양1동,34359,1439,748,479,357,193,60,18,5,3106,0.090398
18,화곡2동,17785,1175,789,574,342,121,40,12,0,2932,0.164858
19,등촌1동,24991,1003,678,475,445,291,130,25,8,2764,0.110600

In [31]:
data = data[['동별', '소계', '65세 이상', '65세 이상 비율']]
data.columns = ['행정동', '인구 (명)', '65세 이상', '65세 이상 비율']
data

     행정동  인구 (명)  65세 이상  65세 이상 비율
0   화곡1동   52647    8353   0.158661
1   방화1동   42851    6674   0.155749
2   등촌3동   30025    6474   0.215620
3   우장산동   42883    5945   0.138633
4   방화3동   22544    5141   0.228043
5   화곡본동   34121    4899   0.143577
6   발산1동   36236    4832   0.133348
7   방화2동   23371    4690   0.200676
8    염창동   41628    4409   0.105914
9   화곡8동   24415    4394   0.179971
10   공항동   30927    4180   0.135157
11  화곡3동   21603    4102   0.189881
12  가양2동   13902    4083   0.293699
13  화곡6동   25303    3950   0.156108
14  화곡4동   20514    3840   0.187189
15  가양3동   14678    3633   0.247513
16  등촌2동   19855    3183   0.160312
17  가양1동   34359    3106   0.090398
18  화곡2동   17785    2932   0.164858
19  등촌1동   24991    2764   0.110600

### 데이터 합치기

In [40]:
dong.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   행정동         20 non-null     object
 1   인구 (명)      20 non-null     int64
 2   면적 (㎢)      20 non-null     float64
 3   인구밀도 (명/㎢)  20 non-null     int64
dtypes: float64(1), int64(2), object(1)
memory usage: 768.0+ bytes

In [39]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   행정동        20 non-null     object
 1   인구 (명)     20 non-null     int64
 2   65세 이상     20 non-null     int64
 3   65세 이상 비율  20 non-null     float64
dtypes: float64(1), int64(2), object(1)
memory usage: 768.0+ bytes

In [51]:
df = pd.merge(dong, data)
df = df.rename(columns={'인구 (명)':'행정동 인구 (명)', '면적 (㎢)':'행정동 면적 (㎢)', '인구밀도 (명/㎢)':'행정동 인구밀도 (명/㎢)', '65세 이상':'행정동 고령인구수', '65세 이상 비율':'행정동 고령인구비율'})
df

     행정동  행정동 인구 (명)  행정동 면적 (㎢)  행정동 인구밀도 (명/㎢)  행정동 고령인구수  행정동 고령인구비율
0    염창동       41628        1.74           23924       4409    0.105914
1   등촌1동       24991        0.64           39048       2764    0.110600
2   등촌2동       19855        0.92           21582       3183    0.160312
3   등촌3동       30025        0.79           38006       6474    0.215620
4   화곡본동       34121        0.98           34817       4899    0.143577
5   화곡2동       17785        0.45           39522       2932    0.164858
6   화곡3동       21603        0.53           40760       4102    0.189881
7   화곡4동       20514        0.82           25017       3840    0.187189
8   화곡6동       25303        1.11           22795       3950    0.156108
9   화곡8동       24415        0.53           46066       4394    0.179971
10  가양1동       34359        4.70            7310       3106    0.090398
11  가양2동       13902        1.00           13902       4083    0.293699
12  가양3동       14678        0.50           29356       3633    0.247513
13  발산1동       36236        2.94           12325       4832    0.133348
14   공항동       30927       10.87            2845       4180    0.135157
15  방화1동       42851        1.48           28953       6674    0.155749
16  방화2동       23371        6.41            3646       4690    0.200676
17  방화3동       22544        2.55            8841       5141    0.228043
18  화곡1동       52647        1.12           47006       8353    0.158661
19  우장산동       42883        1.36           31532       5945    0.138633

In [52]:
df['행정동 고령인구비율'] = df['행정동 고령인구비율'].round(2)
df

     행정동  행정동 인구 (명)  행정동 면적 (㎢)  행정동 인구밀도 (명/㎢)  행정동 고령인구수  행정동 고령인구비율
0    염창동       41628        1.74           23924       4409        0.11
1   등촌1동       24991        0.64           39048       2764        0.11
2   등촌2동       19855        0.92           21582       3183        0.16
3   등촌3동       30025        0.79           38006       6474        0.22
4   화곡본동       34121        0.98           34817       4899        0.14
5   화곡2동       17785        0.45           39522       2932        0.16
6   화곡3동       21603        0.53           40760       4102        0.19
7   화곡4동       20514        0.82           25017       3840        0.19
8   화곡6동       25303        1.11           22795       3950        0.16
9   화곡8동       24415        0.53           46066       4394        0.18
10  가양1동       34359        4.70            7310       3106        0.09
11  가양2동       13902        1.00           13902       4083        0.29
12  가양3동       14678        0.50           29356       3633        0.25
13  발산1동       36236        2.94           12325       4832        0.13
14   공항동       30927       10.87            2845       4180        0.14
15  방화1동       42851        1.48           28953       6674        0.16
16  방화2동       23371        6.41            3646       4690        0.20
17  방화3동       22544        2.55            8841       5141        0.23
18  화곡1동       52647        1.12           47006       8353        0.16
19  우장산동       42883        1.36           31532       5945        0.14

### 헹정동 고령인구밀도 컬럼 생성

In [53]:
df['행정동 고령인구밀도'] = (df['행정동 고령인구수'] / df['행정동 면적 (㎢)']).round(2)
df

,행정동,행정동 인구 (명),행정동 면적 (㎢),행정동 인구밀도 (명/㎢),행정동 고령인구수,행정동 고령인구비율,행정동 고령인구밀도
0,염창동,41628,1.74,23924,4409,0.11,2533.91
1,등촌1동,24991,0.64,39048,2764,0.11,4318.75
2,등촌2동,19855,0.92,21582,3183,0.16,3459.78
3,등촌3동,30025,0.79,38006,6474,0.22,8194.94
4,화곡본동,34121,0.98,34817,4899,0.14,4998.98
5,화곡2동,17785,0.45,39522,2932,0.16,6515.56
6,화곡3동,21603,0.53,40760,4102,0.19,7739.62
7,화곡4동,20514,0.82,25017,3840,0.19,4682.93
8,화곡6동,25303,1.11,22795,3950,0.16,3558.56
9,화곡8동,24415,0.53,46066,4394,0.18,8290.57
10,가양1동,34359,4.70,7310,3106,0.09,660.85
11,가양2동,13902,1.00,13902,4083,0.29,4083.00
12,가양3동,14678,0.50,29356,3633,0.25,7266.00
13,발산1동,36236,2.94,12325,4832,0.13,1643.54
14,공항동,30927,10.87,2845,4180,0.14,384.54
15,방화1동,42851,1.48,28953,6674,0.16,4509.46
16,방화2동,23371,6.41,3646,4690,0.20,731.67
17,방화3동,22544,2.55,8841,5141,0.23,2016.08
18,화곡1동,52647,1.12,47006,8353,0.16,7458.04
19,우장산동,42883,1.36,31532,5945,0.14,4371.32

### 저장

In [55]:
df.to_csv('data/fixed/행정동별 고령인구 feature.csv', index=False)

### [추가] 수급자수 합계 컬럼 생성

In [78]:
path = 'C:/Users/User/aivle_gangseo/기초생활수급자/data/fixed/65세이상_자격별수급자수.csv'
df2 = pd.read_csv(path)
df2

     행정동  65세이상생계급여수급자  65세이상주거급여수급자  65세이상의료급여수급자
0    염창동            49            37             4
1   등촌1동            77            29             3
2   등촌2동           105            31             6
3   등촌3동          2128           347           127
4   화곡1동           469           177            24
5   화곡2동           191            70            22
6   화곡3동           164            64            17
7   화곡4동           268           112            20
8   화곡본동           338           143            25
9   화곡6동           232           103            21
10  화곡8동           250           104            14
11  가양1동            35            42             6
12  가양2동          1316           269            88
13  가양3동           873           208            56
14  발산1동           213           197            22
15  우장산동           121           106             8
16   공항동           330           174            29
17  방화1동           311           110            18
18  방화2동           594           148            40
19  방화3동           876           180            57

In [79]:
df2['기초생활수급자 고령인구수 (생계/주거/의료)'] = df2.sum(axis=1)
df2

     행정동  65세이상생계급여수급자  65세이상주거급여수급자  65세이상의료급여수급자  기초생활수급자 고령인구수 (생계/주거/의료)
0    염창동            49            37             4                        90
1   등촌1동            77            29             3                       109
2   등촌2동           105            31             6                       142
3   등촌3동          2128           347           127                      2602
4   화곡1동           469           177            24                       670
5   화곡2동           191            70            22                       283
6   화곡3동           164            64            17                       245
7   화곡4동           268           112            20                       400
8   화곡본동           338           143            25                       506
9   화곡6동           232           103            21                       356
10  화곡8동           250           104            14                       368
11  가양1동            35            42             6                        83
12  가양2동          1316           269            88                      1673
13  가양3동           873           208            56                      1137
14  발산1동           213           197            22                       432
15  우장산동           121           106             8                       235
16   공항동           330           174            29                       533
17  방화1동           311           110            18                       439
18  방화2동           594           148            40                       782
19  방화3동           876           180            57                      1113

In [80]:
df3 = df2[['행정동','기초생활수급자 고령인구수 (생계/주거/의료)']]
df3

     행정동  기초생활수급자 고령인구수 (생계/주거/의료)
0    염창동                        90
1   등촌1동                       109
2   등촌2동                       142
3   등촌3동                      2602
4   화곡1동                       670
5   화곡2동                       283
6   화곡3동                       245
7   화곡4동                       400
8   화곡본동                       506
9   화곡6동                       356
10  화곡8동                       368
11  가양1동                        83
12  가양2동                      1673
13  가양3동                      1137
14  발산1동                       432
15  우장산동                       235
16   공항동                       533
17  방화1동                       439
18  방화2동                       782
19  방화3동                      1113

In [81]:
merge_df = pd.merge(df, df3)
merge_df

,행정동,행정동 인구 (명),행정동 면적 (㎢),행정동 인구밀도 (명/㎢),행정동 고령인구수,행정동 고령인구비율,행정동 고령인구밀도,기초생활수급자 고령인구수 (생계/주거/의료)
0,염창동,41628,1.74,23924,4409,0.11,2533.91,90
1,등촌1동,24991,0.64,39048,2764,0.11,4318.75,109
2,등촌2동,19855,0.92,21582,3183,0.16,3459.78,142
3,등촌3동,30025,0.79,38006,6474,0.22,8194.94,2602
4,화곡본동,34121,0.98,34817,4899,0.14,4998.98,506
5,화곡2동,17785,0.45,39522,2932,0.16,6515.56,283
6,화곡3동,21603,0.53,40760,4102,0.19,7739.62,245
7,화곡4동,20514,0.82,25017,3840,0.19,4682.93,400
8,화곡6동,25303,1.11,22795,3950,0.16,3558.56,356
9,화곡8동,24415,0.53,46066,4394,0.18,8290.57,368
10,가양1동,34359,4.70,7310,3106,0.09,660.85,83
11,가양2동,13902,1.00,13902,4083,0.29,4083.00,1673
12,가양3동,14678,0.50,29356,3633,0.25,7266.00,1137
13,발산1동,36236,2.94,12325,4832,0.13,1643.54,432
14,공항동,30927,10.87,2845,4180,0.14,384.54,533
15,방화1동,42851,1.48,28953,6674,0.16,4509.46,439
16,방화2동,23371,6.41,3646,4690,0.20,731.67,782
17,방화3동,22544,2.55,8841,5141,0.23,2016.08,1113
18,화곡1동,52647,1.12,47006,8353,0.16,7458.04,670
19,우장산동,42883,1.36,31532,5945,0.14,4371.32,235

### 기초생활수급자 고령인구밀도 컬럼 생성

In [83]:
merge_df['기초생활수급자 고령인구밀도 (생계/주거/의료)'] = (merge_df['기초생활수급자 고령인구수 (생계/주거/의료)'] / merge_df['행정동 면적 (㎢)']).round(2)
merge_df

,행정동,행정동 인구 (명),행정동 면적 (㎢),행정동 인구밀도 (명/㎢),행정동 고령인구수,행정동 고령인구비율,행정동 고령인구밀도,기초생활수급자 고령인구수 (생계/주거/의료),기초생활수급자 고령인구밀도 (생계/주거/의료)
0,염창동,41628,1.74,23924,4409,0.11,2533.91,90,51.72
1,등촌1동,24991,0.64,39048,2764,0.11,4318.75,109,170.31
2,등촌2동,19855,0.92,21582,3183,0.16,3459.78,142,154.35
3,등촌3동,30025,0.79,38006,6474,0.22,8194.94,2602,3293.67
4,화곡본동,34121,0.98,34817,4899,0.14,4998.98,506,516.33
5,화곡2동,17785,0.45,39522,2932,0.16,6515.56,283,628.89
6,화곡3동,21603,0.53,40760,4102,0.19,7739.62,245,462.26
7,화곡4동,20514,0.82,25017,3840,0.19,4682.93,400,487.80
8,화곡6동,25303,1.11,22795,3950,0.16,3558.56,356,320.72
9,화곡8동,24415,0.53,46066,4394,0.18,8290.57,368,694.34
10,가양1동,34359,4.70,7310,3106,0.09,660.85,83,17.66
11,가양2동,13902,1.00,13902,4083,0.29,4083.00,1673,1673.00
12,가양3동,14678,0.50,29356,3633,0.25,7266.00,1137,2274.00
13,발산1동,36236,2.94,12325,4832,0.13,1643.54,432,146.94
14,공항동,30927,10.87,2845,4180,0.14,384.54,533,49.03
15,방화1동,42851,1.48,28953,6674,0.16,4509.46,439,296.62
16,방화2동,23371,6.41,3646,4690,0.20,731.67,782,122.00
17,방화3동,22544,2.55,8841,5141,0.23,2016.08,1113,436.47
18,화곡1동,52647,1.12,47006,8353,0.16,7458.04,670,598.21
19,우장산동,42883,1.36,31532,5945,0.14,4371.32,235,172.79

In [91]:
merge_df.to_csv('data/fixed/features.csv', index=False)

In [94]:
pd.read_csv('data/fixed/features.csv')

,행정동,행정동 인구 (명),행정동 면적 (㎢),행정동 인구밀도 (명/㎢),행정동 고령인구수,행정동 고령인구비율,행정동 고령인구밀도,기초생활수급자 고령인구수 (생계/주거/의료),기초생활수급자 고령인구밀도 (생계/주거/의료)
0,염창동,41628,1.74,23924,4409,0.11,2533.91,90,51.72
1,등촌1동,24991,0.64,39048,2764,0.11,4318.75,109,170.31
2,등촌2동,19855,0.92,21582,3183,0.16,3459.78,142,154.35
3,등촌3동,30025,0.79,38006,6474,0.22,8194.94,2602,3293.67
4,화곡본동,34121,0.98,34817,4899,0.14,4998.98,506,516.33
5,화곡2동,17785,0.45,39522,2932,0.16,6515.56,283,628.89
6,화곡3동,21603,0.53,40760,4102,0.19,7739.62,245,462.26
7,화곡4동,20514,0.82,25017,3840,0.19,4682.93,400,487.80
8,화곡6동,25303,1.11,22795,3950,0.16,3558.56,356,320.72
9,화곡8동,24415,0.53,46066,4394,0.18,8290.57,368,694.34
10,가양1동,34359,4.70,7310,3106,0.09,660.85,83,17.66
11,가양2동,13902,1.00,13902,4083,0.29,4083.00,1673,1673.00
12,가양3동,14678,0.50,29356,3633,0.25,7266.00,1137,2274.00
13,발산1동,36236,2.94,12325,4832,0.13,1643.54,432,146.94
14,공항동,30927,10.87,2845,4180,0.14,384.54,533,49.03
15,방화1동,42851,1.48,28953,6674,0.16,4509.46,439,296.62
16,방화2동,23371,6.41,3646,4690,0.20,731.67,782,122.00
17,방화3동,22544,2.55,8841,5141,0.23,2016.08,1113,436.47
18,화곡1동,52647,1.12,47006,8353,0.16,7458.04,670,598.21
19,우장산동,42883,1.36,31532,5945,0.14,4371.32,235,172.79

In [95]:
merge_df = pd.read_csv('data/fixed/features.csv')
merge_df

,행정동,행정동 인구 (명),행정동 면적 (㎢),행정동 인구밀도 (명/㎢),행정동 고령인구수,행정동 고령인구비율,행정동 고령인구밀도,기초생활수급자 고령인구수 (생계/주거/의료),기초생활수급자 고령인구밀도 (생계/주거/의료)
0,염창동,41628,1.74,23924,4409,0.11,2533.91,90,51.72
1,등촌1동,24991,0.64,39048,2764,0.11,4318.75,109,170.31
2,등촌2동,19855,0.92,21582,3183,0.16,3459.78,142,154.35
3,등촌3동,30025,0.79,38006,6474,0.22,8194.94,2602,3293.67
4,화곡본동,34121,0.98,34817,4899,0.14,4998.98,506,516.33
5,화곡2동,17785,0.45,39522,2932,0.16,6515.56,283,628.89
6,화곡3동,21603,0.53,40760,4102,0.19,7739.62,245,462.26
7,화곡4동,20514,0.82,25017,3840,0.19,4682.93,400,487.80
8,화곡6동,25303,1.11,22795,3950,0.16,3558.56,356,320.72
9,화곡8동,24415,0.53,46066,4394,0.18,8290.57,368,694.34
10,가양1동,34359,4.70,7310,3106,0.09,660.85,83,17.66
11,가양2동,13902,1.00,13902,4083,0.29,4083.00,1673,1673.00
12,가양3동,14678,0.50,29356,3633,0.25,7266.00,1137,2274.00
13,발산1동,36236,2.94,12325,4832,0.13,1643.54,432,146.94
14,공항동,30927,10.87,2845,4180,0.14,384.54,533,49.03
15,방화1동,42851,1.48,28953,6674,0.16,4509.46,439,296.62
16,방화2동,23371,6.41,3646,4690,0.20,731.67,782,122.00
17,방화3동,22544,2.55,8841,5141,0.23,2016.08,1113,436.47
18,화곡1동,52647,1.12,47006,8353,0.16,7458.04,670,598.21
19,우장산동,42883,1.36,31532,5945,0.14,4371.32,235,172.79

In [112]:
old_alone = pd.read_excel('data/강서구 연령별 동별 독거노인 현황 2021.xlsx')
old_alone

,동별(1),동별(2),동별(3),소계,소계.1,소계.2,국민기초생활보장 수급권자,국민기초생활보장 수급권자.1,국민기초생활보장 수급권자.2,저소득노인,저소득노인.1,저소득노인.2,일 반,일 반.1,일 반.2
0,동별(1),동별(2),동별(3),계,65~79세,80세 이상,계,65~79세,80세 이상,계,65~79세,80세 이상,계,65~79세,80세 이상
1,서울특별시,강서구,소계,22863,17209,5654,8818,6046,2772,698,402,296,13347,10761,2586
2,서울특별시,강서구,염창동,629,487,142,73,42,31,15,8,7,541,437,104
3,서울특별시,강서구,등촌1동,758,419,339,86,56,30,12,5,7,660,358,302
4,서울특별시,강서구,등촌2동,530,398,132,106,66,40,17,9,8,407,323,84
5,서울특별시,강서구,등촌3동,2696,1863,833,1777,1247,530,61,31,30,858,585,273
6,서울특별시,강서구,화곡본동,1212,960,252,404,260,144,59,28,31,749,672,77
7,서울특별시,강서구,화곡2동,674,531,143,216,153,63,29,17,12,429,361,68
8,서울특별시,강서구,화곡3동,781,583,198,183,116,67,13,9,4,585,458,127
9,서울특별시,강서구,화곡4동,903,728,175,303,208,95,30,16,14,570,504,66
10,서울특별시,강서구,화곡6동,917,711,206,270,162,108,32,20,12,615,529,86
11,서울특별시,강서구,화곡8동,1011,832,179,272,192,80,40,29,11,699,611,88
12,서울특별시,강서구,가양1동,539,413,126,67,34,33,19,9,10,453,370,83
13,서울특별시,강서구,가양2동,1690,1253,437,1205,838,367,44,29,15,441,386,55
14,서울특별시,강서구,가양3동,1328,986,342,817,561,256,43,28,15,468,397,71
15,서울특별시,강서구,발산1동,893,699,194,281,188,93,42,27,15,570,484,86
16,서울특별시,강서구,공항동,1021,816,205,333,235,98,55,35,20,633,546,87
17,서울특별시,강서구,방화1동,1228,936,292,307,201,106,50,26,24,871,709,162
18,서울특별시,강서구,방화2동,1449,1078,371,609,417,192,40,27,13,800,634,166
19,서울특별시,강서구,방화3동,1722,1262,460,818,572,246,27,15,12,877,675,202
20,서울특별시,강서구,화곡1동,1978,1559,419,522,384,138,58,30,28,1398,1145,253
21,서울특별시,강서구,우장산동,904,695,209,169,114,55,12,4,8,723,577,146

In [113]:
old_alone.columns

Index(['동별(1)', '동별(2)', '동별(3)', '소계', '소계.1', '소계.2', '국민기초생활보장 수급권자',
       '국민기초생활보장 수급권자.1', '국민기초생활보장 수급권자.2', '저소득노인', '저소득노인.1', '저소득노인.2',
       '일   반', '일   반.1', '일   반.2'],
      dtype='object')

In [114]:
old_alone = old_alone[['동별(3)', '소계']]
old_alone

    동별(3)     소계
0   동별(3)      계
1      소계  22863
2     염창동    629
3    등촌1동    758
4    등촌2동    530
5    등촌3동   2696
6    화곡본동   1212
7    화곡2동    674
8    화곡3동    781
9    화곡4동    903
10   화곡6동    917
11   화곡8동   1011
12   가양1동    539
13   가양2동   1690
14   가양3동   1328
15   발산1동    893
16    공항동   1021
17   방화1동   1228
18   방화2동   1449
19   방화3동   1722
20   화곡1동   1978
21   우장산동    904

In [115]:
old_alone = old_alone.iloc[2:]

In [116]:
old_alone.columns = ['행정동', '행정동 독거노인수']

In [117]:
old_alone.reset_index(drop=True, inplace=True)
old_alone

     행정동 행정동 독거노인수
0    염창동       629
1   등촌1동       758
2   등촌2동       530
3   등촌3동      2696
4   화곡본동      1212
5   화곡2동       674
6   화곡3동       781
7   화곡4동       903
8   화곡6동       917
9   화곡8동      1011
10  가양1동       539
11  가양2동      1690
12  가양3동      1328
13  발산1동       893
14   공항동      1021
15  방화1동      1228
16  방화2동      1449
17  방화3동      1722
18  화곡1동      1978
19  우장산동       904

In [119]:
merge_df = pd.merge(merge_df, old_alone)
merge_df

,행정동,행정동 인구 (명),행정동 면적 (㎢),행정동 인구밀도 (명/㎢),행정동 고령인구수,행정동 고령인구비율,행정동 고령인구밀도,기초생활수급자 고령인구수 (생계/주거/의료),기초생활수급자 고령인구밀도 (생계/주거/의료),행정동 독거노인수
0,염창동,41628,1.74,23924,4409,0.11,2533.91,90,51.72,629
1,등촌1동,24991,0.64,39048,2764,0.11,4318.75,109,170.31,758
2,등촌2동,19855,0.92,21582,3183,0.16,3459.78,142,154.35,530
3,등촌3동,30025,0.79,38006,6474,0.22,8194.94,2602,3293.67,2696
4,화곡본동,34121,0.98,34817,4899,0.14,4998.98,506,516.33,1212
5,화곡2동,17785,0.45,39522,2932,0.16,6515.56,283,628.89,674
6,화곡3동,21603,0.53,40760,4102,0.19,7739.62,245,462.26,781
7,화곡4동,20514,0.82,25017,3840,0.19,4682.93,400,487.80,903
8,화곡6동,25303,1.11,22795,3950,0.16,3558.56,356,320.72,917
9,화곡8동,24415,0.53,46066,4394,0.18,8290.57,368,694.34,1011
10,가양1동,34359,4.70,7310,3106,0.09,660.85,83,17.66,539
11,가양2동,13902,1.00,13902,4083,0.29,4083.00,1673,1673.00,1690
12,가양3동,14678,0.50,29356,3633,0.25,7266.00,1137,2274.00,1328
13,발산1동,36236,2.94,12325,4832,0.13,1643.54,432,146.94,893
14,공항동,30927,10.87,2845,4180,0.14,384.54,533,49.03,1021
15,방화1동,42851,1.48,28953,6674,0.16,4509.46,439,296.62,1228
16,방화2동,23371,6.41,3646,4690,0.20,731.67,782,122.00,1449
17,방화3동,22544,2.55,8841,5141,0.23,2016.08,1113,436.47,1722
18,화곡1동,52647,1.12,47006,8353,0.16,7458.04,670,598.21,1978
19,우장산동,42883,1.36,31532,5945,0.14,4371.32,235,172.79,904

In [120]:
merge_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20 entries, 0 to 19
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   행정동                        20 non-null     object
 1   행정동 인구 (명)                 20 non-null     int64
 2   행정동 면적 (㎢)                 20 non-null     float64
 3   행정동 인구밀도 (명/㎢)             20 non-null     int64
 4   행정동 고령인구수                  20 non-null     int64
 5   행정동 고령인구비율                 20 non-null     float64
 6   행정동 고령인구밀도                 20 non-null     float64
 7   기초생활수급자 고령인구수 (생계/주거/의료)   20 non-null     int64
 8   기초생활수급자 고령인구밀도 (생계/주거/의료)  20 non-null     float64
 9   행정동 독거노인수                  20 non-null     object
dtypes: float64(4), int64(4), object(2)
memory usage: 1.7+ KB

In [121]:
merge_df['행정동 독거노인수'] = merge_df['행정동 독거노인수'].astype('int64')

In [122]:
merge_df['행정동 독거노인비율'] = (merge_df['행정동 독거노인수'] / merge_df['행정동 인구 (명)']).round(2)
merge_df

,행정동,행정동 인구 (명),행정동 면적 (㎢),행정동 인구밀도 (명/㎢),행정동 고령인구수,행정동 고령인구비율,행정동 고령인구밀도,기초생활수급자 고령인구수 (생계/주거/의료),기초생활수급자 고령인구밀도 (생계/주거/의료),행정동 독거노인수,행정동 독거노인비율
0,염창동,41628,1.74,23924,4409,0.11,2533.91,90,51.72,629,0.02
1,등촌1동,24991,0.64,39048,2764,0.11,4318.75,109,170.31,758,0.03
2,등촌2동,19855,0.92,21582,3183,0.16,3459.78,142,154.35,530,0.03
3,등촌3동,30025,0.79,38006,6474,0.22,8194.94,2602,3293.67,2696,0.09
4,화곡본동,34121,0.98,34817,4899,0.14,4998.98,506,516.33,1212,0.04
5,화곡2동,17785,0.45,39522,2932,0.16,6515.56,283,628.89,674,0.04
6,화곡3동,21603,0.53,40760,4102,0.19,7739.62,245,462.26,781,0.04
7,화곡4동,20514,0.82,25017,3840,0.19,4682.93,400,487.80,903,0.04
8,화곡6동,25303,1.11,22795,3950,0.16,3558.56,356,320.72,917,0.04
9,화곡8동,24415,0.53,46066,4394,0.18,8290.57,368,694.34,1011,0.04
10,가양1동,34359,4.70,7310,3106,0.09,660.85,83,17.66,539,0.02
11,가양2동,13902,1.00,13902,4083,0.29,4083.00,1673,1673.00,1690,0.12
12,가양3동,14678,0.50,29356,3633,0.25,7266.00,1137,2274.00,1328,0.09
13,발산1동,36236,2.94,12325,4832,0.13,1643.54,432,146.94,893,0.02
14,공항동,30927,10.87,2845,4180,0.14,384.54,533,49.03,1021,0.03
15,방화1동,42851,1.48,28953,6674,0.16,4509.46,439,296.62,1228,0.03
16,방화2동,23371,6.41,3646,4690,0.20,731.67,782,122.00,1449,0.06
17,방화3동,22544,2.55,8841,5141,0.23,2016.08,1113,436.47,1722,0.08
18,화곡1동,52647,1.12,47006,8353,0.16,7458.04,670,598.21,1978,0.04
19,우장산동,42883,1.36,31532,5945,0.14,4371.32,235,172.79,904,0.02

In [123]:
merge_df['행정동 독거노인밀도'] = (merge_df['행정동 독거노인수'] / merge_df['행정동 면적 (㎢)']).round(2)
merge_df

,행정동,행정동 인구 (명),행정동 면적 (㎢),행정동 인구밀도 (명/㎢),행정동 고령인구수,행정동 고령인구비율,행정동 고령인구밀도,기초생활수급자 고령인구수 (생계/주거/의료),기초생활수급자 고령인구밀도 (생계/주거/의료),행정동 독거노인수,행정동 독거노인비율,행정동 독거노인밀도
0,염창동,41628,1.74,23924,4409,0.11,2533.91,90,51.72,629,0.02,361.49
1,등촌1동,24991,0.64,39048,2764,0.11,4318.75,109,170.31,758,0.03,1184.38
2,등촌2동,19855,0.92,21582,3183,0.16,3459.78,142,154.35,530,0.03,576.09
3,등촌3동,30025,0.79,38006,6474,0.22,8194.94,2602,3293.67,2696,0.09,3412.66
4,화곡본동,34121,0.98,34817,4899,0.14,4998.98,506,516.33,1212,0.04,1236.73
5,화곡2동,17785,0.45,39522,2932,0.16,6515.56,283,628.89,674,0.04,1497.78
6,화곡3동,21603,0.53,40760,4102,0.19,7739.62,245,462.26,781,0.04,1473.58
7,화곡4동,20514,0.82,25017,3840,0.19,4682.93,400,487.80,903,0.04,1101.22
8,화곡6동,25303,1.11,22795,3950,0.16,3558.56,356,320.72,917,0.04,826.13
9,화곡8동,24415,0.53,46066,4394,0.18,8290.57,368,694.34,1011,0.04,1907.55
10,가양1동,34359,4.70,7310,3106,0.09,660.85,83,17.66,539,0.02,114.68
11,가양2동,13902,1.00,13902,4083,0.29,4083.00,1673,1673.00,1690,0.12,1690.00
12,가양3동,14678,0.50,29356,3633,0.25,7266.00,1137,2274.00,1328,0.09,2656.00
13,발산1동,36236,2.94,12325,4832,0.13,1643.54,432,146.94,893,0.02,303.74
14,공항동,30927,10.87,2845,4180,0.14,384.54,533,49.03,1021,0.03,93.93
15,방화1동,42851,1.48,28953,6674,0.16,4509.46,439,296.62,1228,0.03,829.73
16,방화2동,23371,6.41,3646,4690,0.20,731.67,782,122.00,1449,0.06,226.05
17,방화3동,22544,2.55,8841,5141,0.23,2016.08,1113,436.47,1722,0.08,675.29
18,화곡1동,52647,1.12,47006,8353,0.16,7458.04,670,598.21,1978,0.04,1766.07
19,우장산동,42883,1.36,31532,5945,0.14,4371.32,235,172.79,904,0.02,664.71

In [124]:
merge_df.columns

Index(['행정동', '행정동 인구 (명)', '행정동 면적 (㎢)', '행정동 인구밀도 (명/㎢)', '행정동 고령인구수',
       '행정동 고령인구비율', '행정동 고령인구밀도', '기초생활수급자 고령인구수 (생계/주거/의료)',
       '기초생활수급자 고령인구밀도 (생계/주거/의료)', '행정동 독거노인수', '행정동 독거노인비율', '행정동 독거노인밀도'],
      dtype='object')

In [125]:
merge_df = merge_df[['행정동', '행정동 인구 (명)', '행정동 면적 (㎢)', '행정동 인구밀도 (명/㎢)', '행정동 고령인구수',
       '행정동 고령인구비율', '행정동 고령인구밀도', '행정동 독거노인수', '행정동 독거노인비율', '행정동 독거노인밀도', '기초생활수급자 고령인구수 (생계/주거/의료)',
       '기초생활수급자 고령인구밀도 (생계/주거/의료)']]

In [126]:
merge_df

,행정동,행정동 인구 (명),행정동 면적 (㎢),행정동 인구밀도 (명/㎢),행정동 고령인구수,행정동 고령인구비율,행정동 고령인구밀도,행정동 독거노인수,행정동 독거노인비율,행정동 독거노인밀도,기초생활수급자 고령인구수 (생계/주거/의료),기초생활수급자 고령인구밀도 (생계/주거/의료)
0,염창동,41628,1.74,23924,4409,0.11,2533.91,629,0.02,361.49,90,51.72
1,등촌1동,24991,0.64,39048,2764,0.11,4318.75,758,0.03,1184.38,109,170.31
2,등촌2동,19855,0.92,21582,3183,0.16,3459.78,530,0.03,576.09,142,154.35
3,등촌3동,30025,0.79,38006,6474,0.22,8194.94,2696,0.09,3412.66,2602,3293.67
4,화곡본동,34121,0.98,34817,4899,0.14,4998.98,1212,0.04,1236.73,506,516.33
5,화곡2동,17785,0.45,39522,2932,0.16,6515.56,674,0.04,1497.78,283,628.89
6,화곡3동,21603,0.53,40760,4102,0.19,7739.62,781,0.04,1473.58,245,462.26
7,화곡4동,20514,0.82,25017,3840,0.19,4682.93,903,0.04,1101.22,400,487.80
8,화곡6동,25303,1.11,22795,3950,0.16,3558.56,917,0.04,826.13,356,320.72
9,화곡8동,24415,0.53,46066,4394,0.18,8290.57,1011,0.04,1907.55,368,694.34
10,가양1동,34359,4.70,7310,3106,0.09,660.85,539,0.02,114.68,83,17.66
11,가양2동,13902,1.00,13902,4083,0.29,4083.00,1690,0.12,1690.00,1673,1673.00
12,가양3동,14678,0.50,29356,3633,0.25,7266.00,1328,0.09,2656.00,1137,2274.00
13,발산1동,36236,2.94,12325,4832,0.13,1643.54,893,0.02,303.74,432,146.94
14,공항동,30927,10.87,2845,4180,0.14,384.54,1021,0.03,93.93,533,49.03
15,방화1동,42851,1.48,28953,6674,0.16,4509.46,1228,0.03,829.73,439,296.62
16,방화2동,23371,6.41,3646,4690,0.20,731.67,1449,0.06,226.05,782,122.00
17,방화3동,22544,2.55,8841,5141,0.23,2016.08,1722,0.08,675.29,1113,436.47
18,화곡1동,52647,1.12,47006,8353,0.16,7458.04,1978,0.04,1766.07,670,598.21
19,우장산동,42883,1.36,31532,5945,0.14,4371.32,904,0.02,664.71,235,172.79

In [127]:
merge_df.to_csv('data/fixed/features_final.csv', index=False)